//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomobileInsuranceManagement_AIM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AIMEntities : DbContext
    {
        public AIMEntities()
            : base("name=AIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivePolicy> ActivePolicies { get; set; }
        public virtual DbSet<Automobile> Automobiles { get; set; }
        public virtual DbSet<AutomobileType> AutomobileTypes { get; set; }
        public virtual DbSet<carmodel> carmodels { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<InsuranceType> InsuranceTypes { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual ObjectResult<RETURNPOLICY_Result> RETURNPOLICY(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RETURNPOLICY_Result>("RETURNPOLICY", userIdParameter);
        }
    
        public virtual ObjectResult<RoleDecider_Result> RoleDecider(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RoleDecider_Result>("RoleDecider", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<byte[]> SP_PasswordEncrypt(string password)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<byte[]>("SP_PasswordEncrypt", passwordParameter);
        }
    
        public virtual ObjectResult<SP_Return_ActivePolicies_Result> SP_Return_ActivePolicies(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Return_ActivePolicies_Result>("SP_Return_ActivePolicies", userIdParameter);
        }
    
        public virtual ObjectResult<SP_ReturnPolicy_Result> SP_ReturnPolicy(Nullable<int> automobileId)
        {
            var automobileIdParameter = automobileId.HasValue ?
                new ObjectParameter("automobileId", automobileId) :
                new ObjectParameter("automobileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ReturnPolicy_Result>("SP_ReturnPolicy", automobileIdParameter);
        }
    }
}
