//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomobileInsuranceManagement_AIM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobile()
        {
            this.ActivePolicies = new HashSet<ActivePolicy>();
        }
    
        public int automobile_Id { get; set; }
        public string model { get; set; }
        public string registration_number { get; set; }
        public string chassis_number { get; set; }
        public string brand { get; set; }
        public int weight { get; set; }
        public int manufacture_year { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> vehicle_Type { get; set; }
        public Nullable<bool> isInsured { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivePolicy> ActivePolicies { get; set; }
        public virtual user user { get; set; }
        public virtual AutomobileType AutomobileType { get; set; }
    }
}
