//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomobileInsuranceManagement_AIM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobile()
        {
            this.ActivePolicies = new HashSet<ActivePolicy>();
            this.transactions = new HashSet<transaction>();
        }
    
        public int automobileId { get; set; }
        public Nullable<int> vehicleTypeId { get; set; }
        public Nullable<int> companyId { get; set; }
        public string registrationNumber { get; set; }
        public string chassisNumber { get; set; }
        public int weight { get; set; }
        public int manufactureYear { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<bool> isInsured { get; set; }
        public Nullable<int> modelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivePolicy> ActivePolicies { get; set; }
        public virtual company company { get; set; }
        public virtual carmodel carmodel { get; set; }
        public virtual user user { get; set; }
        public virtual AutomobileType AutomobileType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
