//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomobileInsuranceManagement_AIM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policy()
        {
            this.ActivePolicies = new HashSet<ActivePolicy>();
        }
    
        public int policyId { get; set; }
        public string policyName { get; set; }
        public Nullable<decimal> claimAmount { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<int> years { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string description { get; set; }
        public Nullable<int> automobileTypeId { get; set; }
        public Nullable<int> insuranceTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivePolicy> ActivePolicies { get; set; }
        public virtual AutomobileType AutomobileType { get; set; }
        public virtual InsuranceType InsuranceType { get; set; }
    }
}
